LMSHandout/LMS/Models/LMSModels/Class.cs
using System;
using System.Collections.Generic;

namespace LMS.Models.LMSModels
{
    public partial class Class
    {
        public Class()
        {
            AssignmentCategories = new HashSet<AssignmentCategory>();
            Enrolleds = new HashSet<Enrolled>();
        }

        public uint ClassId { get; set; }
        public string Season { get; set; } = null!;
        public uint Year { get; set; }
        public string Location { get; set; } = null!;
        public TimeOnly StartTime { get; set; }
        public TimeOnly EndTime { get; set; }
        public uint Listing { get; set; }
        public string? TaughtBy { get; set; } = null;

        public virtual Course ListingNavigation { get; set; } = null!;
        public virtual Professor TaughtByNavigation { get; set; } = null!;
        public virtual ICollection<AssignmentCategory> AssignmentCategories { get; set; }
        public virtual ICollection<Enrolled> Enrolleds { get; set; }
    }
}

LMSHandout/LMS/Models/LMSModels/Student.cs
using System;
using System.Collections.Generic;

namespace LMS.Models.LMSModels
{
    public partial class Student
    {
        public Student()
        {
            Enrolleds = new HashSet<Enrolled>();
            Submissions = new HashSet<Submission>();
        }

        public string UId { get; set; } = null!;
        public string FName { get; set; } = null!;
        public string LName { get; set; } = null!;
        public DateOnly Dob { get; set; }
        public string Major { get; set; } = null!;

        public virtual Department MajorNavigation { get; set; } = null!;
        public virtual ICollection<Enrolled> Enrolleds { get; set; }
        public virtual ICollection<Submission> Submissions { get; set; }
    }
}

LMSHandout/LMS/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using LMS.Models.LMSModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LMS.Controllers
{
    public class CommonController : Controller
    {
        private readonly LMSContext db;

        public CommonController(LMSContext _db)
        {
            db = _db;
        }

        /*******Begin code to modify********/

        /// <summary>
        /// Retreive a JSON array of all departments from the database.
        /// Each object in the array should have a field called "name" and "subject",
        /// where "name" is the department name and "subject" is the subject abbreviation.
        /// </summary>
        /// <returns>The JSON array</returns>
        public IActionResult GetDepartments()
        {
            var departments = db.Departments.Select(d => new
            {
                name = d.Name,
                subject = d.Subject
            }).ToList();

            return Json(departments.ToArray());
        }
        

        /// <summary>
        /// Returns a JSON array representing the course catalog.
        /// Each object in the array should have the following fields:
        /// "subject": The subject abbreviation, (e.g. "CS")
        /// "dname": The department name, as in "Computer Science"
        /// "courses": An array of JSON objects representing the courses in the department.
        ///            Each field in this inner-array should have the following fields:
        ///            "number": The course number (e.g. 5530)
        ///            "cname": The course name (e.g. "Database Systems")
        /// </summary>
        /// <returns>The JSON array</returns>
        public IActionResult GetCatalog()
        {
            var catalog = db.Departments.Select(d => new
            {
                subject = d.Subject,
                dname = d.Name,
                courses = d.Courses.Select(c => new
                {
                    number = c.Number,
                    cname = c.Name
                }).ToList()
            }).ToList();

            return Json(catalog.ToArray());
        }

        /// <summary>
        /// Returns a JSON array of all class offerings of a specific course.
        /// Each object in the array should have the following fields:
        /// "season": the season part of the semester, such as "Fall"
        /// "year": the year part of the semester
        /// "location": the location of the class
        /// "start": the start time in format "hh:mm:ss"
        /// "end": the end time in format "hh:mm:ss"
        /// "fname": the first name of the professor
        /// "lname": the last name of the professor
        /// </summary>
        /// <param name="subject">The subject abbreviation, as in "CS"</param>
        /// <param name="number">The course number, as in 5530</param>
        /// <returns>The JSON array</returns>
        public IActionResult GetClassOfferings(string subject, int number)
        {
            var classOfferings = db.Courses
                .Where(c => c.Department == subject && c.Number == number)
                .SelectMany(c => c.Classes)
                .Select(cls => new
                {
                    season = cls.Season,
                    year = cls.Year,
                    location = cls.Location,
                    start = cls.StartTime.ToString(),
                    end = cls.EndTime.ToString(),
                    fname = cls.TaughtByNavigation.FName,
                    lname = cls.TaughtByNavigation.LName
                }).ToList();

            return Json(classOfferings.ToArray());
        }

        /// <summary>
        /// This method does NOT return JSON. It returns plain text (containing html).
        /// Use "return Content(...)" to return plain text.
        /// Returns the contents of an assignment.
        /// </summary>
        /// <param name="subject">The course subject abbreviation</param>
        /// <param name="num">The course number</param>
        /// <param name="season">The season part of the semester for the class the assignment belongs to</param>
        /// <param name="year">The year part of the semester for the class the assignment belongs to</param>
        /// <param name="category">The name of the assignment category in the class</param>
        /// <param name="asgname">The name of the assignment in the category</param>
        /// <returns>The assignment contents</returns>
        public IActionResult GetAssignmentContents(string subject, int num, string season, int year, string category, string asgname)
        {
            var assignmentContents = db.Assignments
                .Where(a => a.CategoryNavigation.InClassNavigation.ListingNavigation.Department == subject &&
                        a.CategoryNavigation.InClassNavigation.ListingNavigation.Number == num &&
                        a.CategoryNavigation.InClassNavigation.Season == season &&
                        a.CategoryNavigation.InClassNavigation.Year == year &&
                        a.CategoryNavigation.Name == category &&
                        a.Name == asgname)
                .Select(a => a.Contents)
                .FirstOrDefault();

            return Content(assignmentContents ?? "");
        }


        /// <summary>
        /// This method does NOT return JSON. It returns plain text (containing html).
        /// Use "return Content(...)" to return plain text.
        /// Returns the contents of an assignment submission.
        /// Returns the empty string ("") if there is no submission.
        /// </summary>
        /// <param name="subject">The course subject abbreviation</param>
        /// <param name="num">The course number</param>
        /// <param name="season">The season part of the semester for the class the assignment belongs to</param>
        /// <param name="year">The year part of the semester for the class the assignment belongs to</param>
        /// <param name="category">The name of the assignment category in the class</param>
        /// <param name="asgname">The name of the assignment in the category</param>
        /// <param name="uid">The uid of the student who submitted it</param>
        /// <returns>The submission text</returns>
        public IActionResult GetSubmissionText(string subject, int num, string season, int year, string category, string asgname, string uid)
        {
            var submissionText = db.Submissions
                .Where(s => s.AssignmentNavigation.CategoryNavigation.InClassNavigation.ListingNavigation.Department == subject &&
                        s.AssignmentNavigation.CategoryNavigation.InClassNavigation.ListingNavigation.Number == num &&
                        s.AssignmentNavigation.CategoryNavigation.InClassNavigation.Season == season &&
                        s.AssignmentNavigation.CategoryNavigation.InClassNavigation.Year == year &&
                        s.AssignmentNavigation.CategoryNavigation.Name == category &&
                        s.AssignmentNavigation.Name == asgname && s.Student == uid)
                .Select(s => s.SubmissionContents)
                .FirstOrDefault();

            return Content(submissionText ?? "");
        }


        /// <summary>
        /// Gets information about a user as a single JSON object.
        /// The object should have the following fields:
        /// "fname": the user's first name
        /// "lname": the user's last name
        /// "uid": the user's uid
        /// "department": (professors and students only) the name (such as "Computer Science") of the department for the user. 
        ///               If the user is a Professor, this is the department they work in.
        ///               If the user is a Student, this is the department they major in.    
        ///               If the user is an Administrator, this field is not present in the returned JSON
        /// </summary>
        /// <param name="uid">The ID of the user</param>
        /// <returns>
        /// The user JSON object 
        /// or an object containing {success: false} if the user doesn't exist
        /// </returns>
        public IActionResult GetUser(string uid)
        {
            var professor = db.Professors.FirstOrDefault(p => p.UId == uid);
            var student = db.Students.FirstOrDefault(s => s.UId == uid);
            var admin = db.Administrators.FirstOrDefault(a => a.UId == uid);

            if (professor != null)
            {
                var userObject = new
                {
                    fname = professor.FName,
                    lname = professor.LName,
                    uid = professor.UId,
                    department = professor.WorksIn
                };

                return Json(userObject);
            }

            if (student != null)
            {
                var userObject = new
                {
                    fname = student.FName,
                    lname = student.LName,
                    uid = student.UId,
                    department = student.Major
                };
                 
                return Json(userObject);
            }

            if (admin != null)
            {
                var userObject = new
                {
                    fname = admin.FName,
                    lname = admin.LName,
                    uid = admin.UId
                };

                return Json(userObject);
            }

            return Json(new { success = false });
        }


        /*******End code to modify********/
    }
}

LMSHandout/LMS/Views/Student/Catalog.cshtml
@{
ViewData["Title"] = "Catalog";
}

<h4 id="topElement">Course Catalog</h4>


@section Scripts
  {
    <script type="text/javascript">

    LoadData();

    //$(function () {
    //  LoadData();
    //});

    function MakeDepartmentTable() {

      var topDiv = document.createElement("div");
      topDiv.setAttribute("class", "col-md-12");

      var panelDiv = document.createElement("div");
      panelDiv.setAttribute("class", "panel panel-primary");

      var headingDiv = document.createElement("div");
      headingDiv.setAttribute("class", "panel-heading");

      var bodyPanel = document.createElement("div");
      bodyPanel.setAttribute("class", "panel-body");

      var tbl = document.createElement("table");
      tbl.setAttribute("class", "table table-bordered table-striped table-responsive table-hover");

      bodyPanel.appendChild(tbl);

      panelDiv.appendChild(headingDiv);
      panelDiv.appendChild(bodyPanel);

      topDiv.appendChild(panelDiv);

      return topDiv;
    }

    function SetDepartmentName(depDiv, name) {

      var heading = depDiv.getElementsByClassName("panel-heading")[0];
      var title = document.createElement("h4");
      title.appendChild(document.createTextNode(name));
      heading.appendChild(title);

    }

    function PopulateTable(tbl, courses, subject) {
      var newBody = document.createElement("tbody");

      courses.sort(function (a, b) {
        return parseInt(a.number) - parseInt(b.number);

      });

      $.each(courses, function (i, item) {
        var tr = document.createElement("tr");

        var td = document.createElement("td");
        var a = document.createElement("a");
        a.setAttribute("href", "/Student/ClassListings/?subject=" + subject + "&num=" + item.number);
        a.appendChild(document.createTextNode(item.number));
        td.appendChild(a);
        tr.appendChild(td);

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.cname));
        tr.appendChild(td);

        newBody.appendChild(tr);
      });

      tbl.appendChild(newBody);

    }

    function LoadData() {


      var prevNode = document.getElementById("topElement");

      $.ajax({
        type: 'GET',
        url: '@Url.Action("GetCatalog", "Common")',
        dataType: 'json',
        success: function (data, status) {
          //alert(JSON.stringify(data));
          $.each(data, function (i, item) {
            var newDiv = MakeDepartmentTable();
            SetDepartmentName(newDiv, item.subject + ": " + item.dname);
            var newTable = newDiv.getElementsByClassName("table")[0];
            PopulateTable(newTable, item.courses, item.subject);

            prevNode.parentNode.insertBefore(newDiv, prevNode.nextSibling);
            prevNode = newDiv;
          });

        },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
        });

    }



    </script>

}

LMSHandout/LMS/Views/Student/Class.cshtml
@{
    ViewData["Title"] = "Class";
}


<h4 id="classname">Class</h4>

<div id="departmentDiv" class="col-md-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Assignments</h3>
        </div>
        <div class="panel-body">
            <table id="tblAssignments" class="table table-bordered table-striped table-responsive table-hover">
                <thead>
                    <tr>
                        <th align="left" class="productth">Name</th>
                        <th align="left" class="productth">Category</th>
                        <th align="left" class="productth">Due</th>
                        <th align="left" class="productth">Score</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>






@section Scripts
  {
    <script type="text/javascript">

    LoadData();

    function PopulateTable(tbl, offerings) {
      var newBody = document.createElement("tbody");


      $.each(offerings, function (i, item) {
        var tr = document.createElement("tr");

        var td = document.createElement("td");
        var a = document.createElement("a");
        a.setAttribute("href", "/Student/Assignment/?subject=" + '@ViewData["subject"]' + "&num=" + '@ViewData["num"]' + "&season=" + '@ViewData["season"]' + "&year=" + '@ViewData["year"]' + "&cat=" + item.cname + "&aname=" + item.aname);
        a.appendChild(document.createTextNode(item.aname));
        td.appendChild(a);
        tr.appendChild(td);

        //var td = document.createElement("td");
        //td.appendChild(document.createTextNode(item.aname));
        //tr.appendChild(td);

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.cname));
        tr.appendChild(td);

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.due));
        tr.appendChild(td);

        var td = document.createElement("td");
        if (item.score != null) {
          td.appendChild(document.createTextNode(item.score));
        }
        else {
          td.appendChild(document.createTextNode("--"));
        }

        tr.appendChild(td);

        newBody.appendChild(tr);
      });

      tbl.appendChild(newBody);

    }

    function LoadData() {

      classname.innerText = '@ViewData["subject"] @ViewData["num"] @ViewData["season"] @ViewData["year"]';

      var tbl = document.getElementById("tblAssignments");

      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetAssignmentsInClass", "Student")',
        dataType: 'json',
        data: {
          subject: '@ViewData["subject"]',
          num: Number('@ViewData["num"]'),
          season: '@ViewData["season"]',
          year: Number('@ViewData["year"]'),
          uid: '@User.Identity.Name'},
        success: function (data, status) {
          //alert(JSON.stringify(data));
          PopulateTable(tbl, data);

        },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
        });


    }

    </script>

}

LMSHandout/LMS/Views/Student/ClassListings.cshtml
@{
    ViewData["Title"] = "ClassListings";   
}

<h4 id="classname">ClassListings</h4>

<div id="departmentDiv" class="col-md-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"></h3>
        </div>
        <div class="panel-body">
            <table id="tblClasses" class="table table-bordered table-striped table-responsive table-hover">
                <thead>
                    <tr>
                        <th align="left" class="productth">Semester</th>
                        <th align="left" class="productth">Location</th>
                        <th align="left" class="productth">Time</th>
                        <th align="left" class="productth">Instructor</th>
                        <th align="left" class="productth">Options</th>
                    </tr>
                </thead>
                @*<tbody></tbody>*@
            </table>
        </div>
    </div>
</div>



@section Scripts
  {
    <script type="text/javascript">

    LoadData();

    function Enroll(_season, _year) {

      $.ajax({
        type: 'POST',
        url: '@Url.Action("Enroll", "Student")',
        dataType: 'json',

        data: {
          subject: '@ViewData["subject"]',
          num: Number('@ViewData["num"]'),
          season: _season,
          year: _year,
          uid: '@User.Identity.Name',
          },
        success: function (data, status) {
          //alert(JSON.stringify(data));
          if (data.success == undefined) {
            alert("Unknown response from controller");
          }
          else if (data.success == true) {
            alert("Successfully enrolled in class");
          }
          else{
            alert("Unable to enroll in class");
          }
        },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
        });

    }

    function PopulateTable(tbl, offerings) {
      var newBody = document.createElement("tbody");

      //courses.sort(function (a, b) {
      //  return parseInt(a.number) - parseInt(b.number);

      //});

      $.each(offerings, function (i, item) {
        var tr = document.createElement("tr");

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.season + " " + item.year));
        tr.appendChild(td);

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.location));
        tr.appendChild(td);

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.start + " - " + item.end));
        tr.appendChild(td);

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.lname + ", " + item.fname));
        tr.appendChild(td);

        var td = document.createElement("td");
        var a = document.createElement("a");
        a.setAttribute("href", "javascript:Enroll('" + item.season + "', '" + item.year + "')");
        a.appendChild(document.createTextNode("enroll"));
        td.appendChild(a);
        tr.appendChild(td);


        newBody.appendChild(tr);
      });

      tbl.appendChild(newBody);

    }

    function LoadData() {

      classname.innerText = 'Offerings of @ViewData["subject"] @ViewData["num"]';

      var tbl = document.getElementById("tblClasses");

      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetClassOfferings", "Common")',
        dataType: 'json',
        data: { subject: '@ViewData["subject"]', number: Number('@ViewData["num"]') },
        success: function (data, status) {

          PopulateTable(tbl, data);

          //alert(JSON.stringify(data));

        },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
        });
    }

    </script>
}

LMSHandout/LMS/Views/Student/Index.cshtml
@{
    ViewData["Title"] = "StudentHome";
}

<h4 id="StudentInfo"></h4>
<h4 id="Major"></h4>
<h4 id="GPA"></h4>

<div class="col-md-12">
    <h4>My Classes</h4>
    <table id="tblClasses" class="table table-bordered table-striped table-responsive table-hover">
        <thead>
            <tr>
                <th align="left" class="productth">Course</th>
                <th align="left" class="productth">Name</th>
                <th align="left" class="productth">Semester</th>
                <th align="left" class="productth">Grade</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

@section Scripts
  {
    <script type="text/javascript">

    LoadData();

    function LoadData() {


      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetUser", "Common")',
        dataType: 'json',
        data: { uid: '@User.Identity.Name' },
        success: function (data, status) {

          if (data.success == false) {
            alert("An error occured when loading user's information");
          }
          else {
            StudentInfo.innerText = data.fname + " " + data.lname + "    " + data.uid;
            Major.innerText = "Major: " + data.department;
          }
        },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
      });

      var tbl = document.getElementById("tblClasses");
      var body = tbl.getElementsByTagName("tbody")[0];
      tbl.removeChild(body);

      var newBody = document.createElement("tbody");


      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetGPA", "Student")',
        dataType: 'json',
        data: { uid: '@User.Identity.Name' },
        success: function (data, status) {

          GPA.innerText = "GPA: " + Number.parseFloat(data.gpa).toFixed(1);

        },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
        });


      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetMyClasses", "Student")',
        dataType: 'json',
        data: { uid: '@User.Identity.Name' },
        success: function (data, status) {

          //alert(JSON.stringify(data));

          $.each(data, function (i, item) {

            var tr = document.createElement("tr");

            var td = document.createElement("td");
            td.appendChild(document.createTextNode(item.subject + item.number));
            tr.appendChild(td);

            var td = document.createElement("td");
            var a = document.createElement("a");
            a.setAttribute("href", "/Student/Class/?subject=" + item.subject + "&num=" + item.number + "&season=" + item.season + "&year=" + item.year);
            a.appendChild(document.createTextNode(item.name));
            td.appendChild(a);
            tr.appendChild(td);

            var td = document.createElement("td");
            td.appendChild(document.createTextNode(item.season + " " + item.year ));
            tr.appendChild(td);

            var td = document.createElement("td");
            td.appendChild(document.createTextNode(item.grade));
            tr.appendChild(td);

            newBody.appendChild(tr);

          });

          tbl.appendChild(newBody);

        },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
        });


      return false;
    }



    </script>

}