LMSHandout/LMS/Models/LMSModels/Administrator.cs
using System;
using System.Collections.Generic;

namespace LMS.Models.LMSModels
{
    public partial class Administrator
    {
        public string UId { get; set; } = null!;
        public string FName { get; set; } = null!;
        public string LName { get; set; } = null!;
        public DateOnly Dob { get; set; }
    }
}

LMSHandout/LMS/Models/LMSModels/Course.cs
using System;
using System.Collections.Generic;

namespace LMS.Models.LMSModels
{
    public partial class Course
    {
        public Course()
        {
            Classes = new HashSet<Class>();
        }

        public uint CatalogId { get; set; }
        public uint Number { get; set; }
        public string Name { get; set; } = null!;
        public string Department { get; set; } = null!;

        public virtual Department DepartmentNavigation { get; set; } = null!;
        public virtual ICollection<Class> Classes { get; set; }
    }
}

LMSHandout/LMS/Models/LMSModels/Department.cs
using System;
using System.Collections.Generic;

namespace LMS.Models.LMSModels
{
    public partial class Department
    {
        public Department()
        {
            Courses = new HashSet<Course>();
            Professors = new HashSet<Professor>();
            Students = new HashSet<Student>();
        }

        public string Name { get; set; } = null!;
        public string Subject { get; set; } = null!;

        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Professor> Professors { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}

LMSHandout/LMS/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using LMS.Models.LMSModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LMS.Controllers
{
    public class AdministratorController : Controller
    {
        private readonly LMSContext db;

        public AdministratorController(LMSContext _db)
        {
            db = _db;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Department(string subject)
        {
            ViewData["subject"] = subject;
            return View();
        }

        public IActionResult Course(string subject, string num)
        {
            ViewData["subject"] = subject;
            ViewData["num"] = num;
            return View();
        }

        /*******Begin code to modify********/

        /// <summary>
        /// Create a department which is uniquely identified by it's subject code
        /// </summary>
        /// <param name="subject">the subject code</param>
        /// <param name="name">the full name of the department</param>
        /// <returns>A JSON object containing {success = true/false}.
        /// false if the department already exists, true otherwise.</returns>
        public IActionResult CreateDepartment(string subject, string name)
        {
            // Check if a department with the given subject already exists in the database
            bool departmentExists = db.Departments.Any(d => d.Subject == subject);
            if (departmentExists){
                return Json(new { success = false });
            }
            else {
                Department department = new Department();
                department.Subject = subject;
                department.Name = name;

                db.Departments.Add(department);
                db.SaveChanges(); // Save changes to the database
                return Json(new { success = true });
            }
            
        }


        /// <summary>
        /// Returns a JSON array of all the courses in the given department.
        /// Each object in the array should have the following fields:
        /// "number" - The course number (as in 5530)
        /// "name" - The course name (as in "Database Systems")
        /// </summary>
        /// <param name="subjCode">The department subject abbreviation (as in "CS")</param>
        /// <returns>The JSON result</returns>
        public IActionResult GetCourses(string subject)
        {
            var courses = db.Courses
                .Where(c => c.Department == subject)
                .Select(c => new { number = c.Number, name = c.Name })
                .ToList();

            return Json(courses);
            //return Json(null);
        }

        /// <summary>
        /// Returns a JSON array of all the professors working in a given department.
        /// Each object in the array should have the following fields:
        /// "lname" - The professor's last name
        /// "fname" - The professor's first name
        /// "uid" - The professor's uid
        /// </summary>
        /// <param name="subject">The department subject abbreviation</param>
        /// <returns>The JSON result</returns>
        public IActionResult GetProfessors(string subject)
        {
            var profs = db.Professors
                .Where(p => p.WorksIn == subject)
                .Select(p => new { fname = p.FName, lname = p.LName, uid = p.UId })
                .ToList();

            return Json(profs);
            
        }


        /// <summary>
        /// Creates a course.
        /// A course is uniquely identified by its number + the subject to which it belongs
        /// </summary>
        /// <param name="subject">The subject abbreviation for the department in which the course will be added</param>
        /// <param name="number">The course number</param>
        /// <param name="name">The course name</param>
        /// <returns>A JSON object containing {success = true/false}.
        /// false if the course already exists, true otherwise.</returns>
        public IActionResult CreateCourse(string subject, int number, string name)
        {
            // Checking if the course already exists
            var existingCourse = db.Courses.FirstOrDefault(c => c.Department == subject && c.Number == number);
            if (existingCourse != null)
            {
                return Json(new { success = false });
            }

            var course = new Course
            {
                Department = subject,
                Number = (ushort)number,
                Name = name
            };

            db.Courses.Add(course);
            db.SaveChanges();

            return Json(new { success = true });
            //return Json(new { success = false });
        }



        /// <summary>
        /// Creates a class offering of a given course.
        /// </summary>
        /// <param name="subject">The department subject abbreviation</param>
        /// <param name="number">The course number</param>
        /// <param name="season">The season part of the semester</param>
        /// <param name="year">The year part of the semester</param>
        /// <param name="start">The start time</param>
        /// <param name="end">The end time</param>
        /// <param name="location">The location</param>
        /// <param name="instructor">The uid of the professor</param>
        /// <returns>A JSON object containing {success = true/false}. 
        /// false if another class occupies the same location during any time 
        /// within the start-end range in the same semester, or if there is already
        /// a Class offering of the same Course in the same Semester,
        /// true otherwise.</returns>
        public IActionResult CreateClass(string subject, int number, string season, int year, DateTime start, DateTime end, string location, string instructor)
        {
            // Find the course
            var course = db.Courses.FirstOrDefault(c => c.Department == subject && c.Number == number);
            if (course == null)
            {
                Console.WriteLine("ERROR: This course has an offering in the same season and year");
                return Json(new { success = false });
            }

            // Check if there is already a class offering of the same course in the same semester
            var existingClass = db.Classes.FirstOrDefault(c =>
                c.Listing == course.CatalogId &&
                c.Season == season &&
                c.Year == year);

            if (existingClass != null)
            {
                Console.WriteLine("ERROR: No such class exists.");
                return Json(new { success = false });
            }

            // Convert DateTime to TimeOnly for start and end times
            TimeOnly startTime = TimeOnly.FromDateTime(start);
            TimeOnly endTime = TimeOnly.FromDateTime(end);

            // Fetch the classes from the database and perform client-side evaluation
            var classes = db.Classes.Where(c =>
                c.Location == location &&
                c.Season == season &&
                c.Year == year).ToList();

            // Check if another class occupies the same location during any time within the start-end range in the same semester
            var conflictingClass = classes.FirstOrDefault(c =>
            {
                // Use TimeOnly directly for comparison
                return !(startTime.CompareTo(c.EndTime) >= 0 || endTime.CompareTo(c.StartTime) <= 0);
            });

            if (conflictingClass != null)
            {
                Console.WriteLine("ERROR: Another class exists at this location for the time mentioned.");
                return Json(new { success = false });
            }

            // Find the professor
            var professor = db.Professors.FirstOrDefault(p => p.UId == instructor);
            if (professor == null)
            {
                Console.WriteLine("ERROR: Professor not found.");
                return Json(new { success = false });
            }

            // Check if the professor has already taught a class in the same time span
            var conflictingProfessorClass = db.Classes.FirstOrDefault(c =>
                c.TaughtBy == instructor &&
                c.Season == season &&
                c.Year == year &&
                !(startTime.CompareTo(c.EndTime) >= 0 || endTime.CompareTo(c.StartTime) <= 0));

            if (conflictingProfessorClass != null)
            {
                Console.WriteLine("ERROR: The professor alreaady has another class for the time mentioned.");
                return Json(new { success = false });
            }

            // Create a new class offering
            var classOffering = new Class
            {
                Listing = course.CatalogId,
                TaughtBy = instructor,
                Year = (ushort)year,
                Season = season,
                StartTime = new TimeOnly(start.Hour, start.Minute, start.Second),
                EndTime = new TimeOnly(end.Hour, end.Minute, end.Second),
                Location = location
            };

            db.Classes.Add(classOffering);
            db.SaveChanges();

            return Json(new { success = true });
            //return Json(new { success = false});
        }
        /*******End code to modify********/

    }
}

LMSHandout/LMS/Views/Administrator/Course.cshtml
@{
    ViewData["Title"] = "Course";
}

<h4 id="classname">Class offerings for @ViewData["subject"] @ViewData["num"]</h4>

<div id="departmentDiv" class="col-md-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"></h3>
        </div>
        <div class="panel-body">
            <table id="tblClasses" class="table table-bordered table-striped table-responsive table-hover">
                <thead>
                    <tr>
                        <th align="left" class="productth">Semester</th>
                        <th align="left" class="productth">Location</th>
                        <th align="left" class="productth">Time</th>
                        <th align="left" class="productth">Instructor</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>


<div class="col-md-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">New Class</h3>
        </div>
        <div class="panel-body">
            <div class="form-group col-md-5">

                <label>Season</label>
                <select id="SeasonSelector">
                    <option value="Spring">Spring</option>
                    <option value="Summer">Summer</option>
                    <option value="Fall">Fall</option>
                </select>

                <input type="text" name="ClassYear" id="ClassYear" class="form-control" placeholder="Enter semester year" required="" />
            </div>
            <div class="form-group col-md-5">

                <div class="control">
                    <label for="start-time">Start Time:</label>
                    <input type="time" id="StartTime" name="StartTime"
                           min="06:00" max="20:00" value="06:00" required />
                </div>
                <div class="control">
                    <label for="end-time">End Time:</label>
                    <input type="time" id="EndTime" name="EndTime"
                           min="06:00" max="20:00" value="07:20" required />
                </div>

            </div>

            <div class="form-group col-md-5">

                <label>Instructor</label>
                <select id="ProfSelector">
                </select>

            </div>

            <div class="form-group col-md-5">

                <label>Location</label>
                <input type="text" name="Location" id="Location" class="form-control" placeholder="Enter location" required="" />

            </div>

            <div class="form-group col-md-1">
                <div style="float: right; display:inline-block;">
                    <input class="btn btn-primary" name="submitButton" id="btnSave" value="Add" type="button" onclick="AddClass()">
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts
  {
    <script type="text/javascript">

    LoadData();

    function AddClass() {

      var claSeason = $("#SeasonSelector").val();
      var claYear = Number($("#ClassYear").val());
      var startTime = $("#StartTime").val();
      var endTime = $("#EndTime").val();
      var prof = $("#ProfSelector").val();
      var loc = $("#Location").val();

      $.ajax({
        type: 'POST',
        url: '@Url.Action("CreateClass", "Administrator")',
        dataType: 'json',
        data: {
          subject: '@ViewData["subject"]',
          number: Number('@ViewData["num"]'),
          season: claSeason,
          year: claYear,
          start: startTime,
          end: endTime,
          location: loc,
          instructor: prof
          },
        success: function (data, status) {
          //alert(JSON.stringify(data));
          if (!data.success) {
            alert("Unable to add class");
          }
          window.location.reload();
        },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
        });

    }


    function PopulateInstructors(selector, instructors) {
      $.each(instructors, function (i, item) {

        var newOption = document.createElement("option");
        newOption.text = item.lname + ", " + item.fname + ": " + item.uid;
        newOption.value = item.uid;
        selector.add(newOption);

      });

    }

    function PopulateTable(tbl, offerings) {
      var newBody = document.createElement("tbody");

      //courses.sort(function (a, b) {
      //  return parseInt(a.number) - parseInt(b.number);

      //});

      $.each(offerings, function (i, item) {
        var tr = document.createElement("tr");

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.season + " " + item.year));
        tr.appendChild(td);

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.location));
        tr.appendChild(td);

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.start + " - " + item.end));
        tr.appendChild(td);

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.lname + ", " + item.fname));
        tr.appendChild(td);

        newBody.appendChild(tr);
      });

      tbl.appendChild(newBody);

    }

    function LoadData() {

      var tbl = document.getElementById("tblClasses");
      var body = tbl.getElementsByTagName("tbody")[0];
      tbl.removeChild(body);

      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetClassOfferings", "Common")',
        dataType: 'json',
        data: {
          subject: '@ViewData["subject"]',
          number: Number('@ViewData["num"]')
        },
          success: function (data, status) {
            //alert(JSON.stringify(data));
            PopulateTable(tbl, data);
          },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
      });

      var selector = document.getElementById("ProfSelector");

      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetProfessors", "Administrator")',
        dataType: 'json',
        data: {
          subject: '@ViewData["subject"]'
        },
          success: function (data, status) {
//            alert(JSON.stringify(data));
            PopulateInstructors(selector, data);
          },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
      });


    }

    </script>

}

LMSHandout/LMS/Views/Administrator/Department.cshtml
@{
    ViewData["Title"] = "Department";
}

<h4 id="classname">Courses in @ViewData["subject"]</h4>

<div id="departmentDiv" class="col-md-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"></h3>
        </div>
        <div class="panel-body">
            <table id="tblCourses" class="table table-bordered table-striped table-responsive table-hover">
                <thead>
                    <tr>
                        <th align="left" class="productth">Number</th>
                        <th align="left" class="productth">Name</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>


<div class="col-md-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">New Course</h3>
        </div>
        <div class="panel-body">
            <div class="form-group col-md-5">
                <label>Course Name</label>
                <input type="text" name="CourseName" id="CourseName" class="form-control" placeholder="Enter course name" required="" />
            </div>
            <div class="form-group col-md-5">
                <label>Course Number</label>
                <input type="text" name="CourseNumber" id="CourseNumber" class="form-control" placeholder="Enter course number" required="" />
            </div>

            <div class="form-group col-md-1">
                <div style="float: right; display:inline-block;">
                    <input class="btn btn-primary" name="submitButton" id="btnSave" value="Add" type="button" onclick="AddCourse()">
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts
  {
    <script type="text/javascript">

    LoadData();

    function AddCourse() {

      var corName = $("#CourseName").val();
      var corNum = Number($("#CourseNumber").val());

      $.ajax({
        type: 'POST',
        url: '@Url.Action("CreateCourse", "Administrator")',
        dataType: 'json',
        data: {
          subject: '@ViewData["subject"]',
          number: corNum,
          name: corName},
        success: function (data, status) {
          //alert(JSON.stringify(data));
          if (!data.success) {
            alert("Unable to add course");
          }
          window.location.reload();
        },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
        });

    }

    function PopulateTable(tbl, offerings) {
      var newBody = document.createElement("tbody");

      offerings.sort(function (a, b) {
        return a.number - b.number;
      });

      $.each(offerings, function (i, item) {
        var tr = document.createElement("tr");

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.number));
        tr.appendChild(td);

        var td = document.createElement("td");
        var a = document.createElement("a");
        a.setAttribute("href", "/Administrator/Course/?subject=" + '@ViewData["subject"]' + "&num=" + item.number);
        a.appendChild(document.createTextNode(item.name));
        td.appendChild(a);
        tr.appendChild(td);

        newBody.appendChild(tr);
      });

      tbl.appendChild(newBody);

    }

    function LoadData() {

      var tbl = document.getElementById("tblCourses");
      var body = tbl.getElementsByTagName("tbody")[0];
      tbl.removeChild(body);

      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetCourses", "Administrator")',
        dataType: 'json',
        data: {
          subject: '@ViewData["subject"]'
        },
          success: function (data, status) {
            //alert(JSON.stringify(data));
            PopulateTable(tbl, data);
          },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
        });
    }

    </script>

}

LMSHandout/LMS/Views/Administrator/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Departments</h2>

<ul id="lstDepartments">
</ul>

<div class="col-md-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">New Department</h3>
        </div>
        <div class="panel-body">
            <div class="form-group col-md-5">
                <label>Subject Code (eg: CS, HIST, ART)</label>
                <input type="text" name="SubjectCode" id="SubjectCode" class="form-control" placeholder="Enter subject code" required="" />
            </div>
            <div class="form-group col-md-5">
                <label>Department Name (eg: Computer Science, History, Art)</label>
                <input type="text" name="DepartmentName" id="DepartmentName" class="form-control" placeholder="Enter department name" required="" />
            </div>

            <div class="form-group col-md-1">
                <div style="float: right; display:inline-block;">
                    <input class="btn btn-primary" name="submitButton" id="btnSave" value="Add" type="button" onclick="AddDepartment()">
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts
  {
    <script type="text/javascript">

    LoadData();


    function PopulateList(lst, departments) {

      departments.sort(function (a, b) {
        return a.subject.localeCompare(b.subject);

      });

      $.each(departments, function (i, item) {
        var li = document.createElement("li");
        var td = document.createElement("td");
        var a = document.createElement("a");
        a.setAttribute("href", "/Administrator/Department/?subject=" + item.subject);
        a.appendChild(document.createTextNode(item.subject));
        li.appendChild(a);
        lst.appendChild(li);
      });

      //tbl.appendChild(newBody);

    }

    function LoadData() {

      var lst = document.getElementById("lstDepartments");

      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetDepartments", "Common")',
        dataType: 'json',
        success: function (data, status) {

          PopulateList(lst, data);

          //alert(JSON.stringify(data));

        },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
        });
    }

    function AddDepartment() {

      let subjCode = $("#SubjectCode").val();
      var deptName = $("#DepartmentName").val();

      $.ajax({
        type: 'POST',
        url: '@Url.Action("CreateDepartment", "Administrator")',
        dataType: 'json',
        data: {
              subject: subjCode,
              name: deptName
          },
        success: function (data, status) {
          //alert(JSON.stringify(data));
          if (!data.success) {
            alert("Unable to add course");
          }
          window.location.reload();
        },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText);
                }
        });

    }

    </script>
}